examcard/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
urlpatterns = [
    path('admin/', admin.site.urls),
    path('installation/',include('installation.urls')),
    path('', include('manager.urls')),
    re_path(r'^media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$',serve,{'document_root':settings.STATIC_ROOT}),
]


urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

handler400 ='errors.views.error_400'
handler403 ='errors.views.error_403'
handler404 ='errors.views.error_404'
handler500='errors.views.error_500'

manager/urls.py
from django.urls import path
from django import views
from . import views
from .views import *
from django.contrib.auth import views as auth_views
urlpatterns=[
    path('',Login.as_view(),name='dashboard'),
    path('accounts/login',Login.as_view(),name='dashboard'),
    path('dashboard',views.home,name='home'),
    path('accounts/logout',views.user_logout,name='logout'),
    path('lock/screen/<str:username>',views.screenLock,name='lock screen'),
    path('unlock/screen/<str:username>',views.screenUnlock,name='unlock screen'),
    path('<str:username>',ProfileView.as_view(),name='profile'),
    path('accounts/register',newStudent.as_view(),name='new student'),
    path('add/school',newSchool.as_view(),name='new school'),
    path('add/courses',newCourse.as_view(),name='new course'),
    path('register/semister',newSem.as_view(),name='new semister'),
    path('site/contact',views.siteContact,name='site contact'),
    path('all/schools',views.schools,name='schools'),
    path('all/courses',views.courses,name='courses'),
    path('site/working/days',views.siteWorking,name='site working days'),
    path('site/social/links',views.siteSocial,name='site social links'),
    path('general/site/settings',General.as_view(),name='general'),
    path('download/exam/card/<pk>',views.download, name='download exam card'),
    path('exam/card/',views.examCard, name='exam card'),
    path('user/password/change/<str:username>',views.passwordChange,name='user password change'),
    path('user/profile/picture/change',views.profilePic,name='user profile picture change'),
    path('accounts/reset/password',auth_views.PasswordResetView.as_view(form_class=UserResetPassword,template_name='panel/password_reset.html'),name='reset_password'),
    path('accounts/reset/password/done',auth_views.PasswordResetDoneView.as_view(template_name='panel/password_reset_done.html'),name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(template_name='panel/password_reset_confirm.html'),name='password_reset_confirm'),
    path('accounts/reset/password/complete',auth_views.PasswordResetCompleteView.as_view(template_name='panel/password_reset_complete.html'),name='password_reset_complete'),


    path('edit/school/<int:id>',editSchool.as_view(),name='edit school'),
    path('delete/school/<int:id>',views.deleteSchool,name='delete school'), 
    path('edit/course/<int:id>',editCourse.as_view(),name='edit course'),
    path('delete/course/<int:id>',views.deleteCourse,name='delete course'),
    path('view/semister/outline',views.semister,name='semister'),

    path('edit/semister/outline/<int:id>',editOutline.as_view(),name='edit outline'),
    path('delete/semister/outline/<int:id>',views.deleteOutline,name='delete outline'), 
    path('view/students',views.allStudents,name='students'), 

    path('edit/student/<int:id>',editStudent.as_view(),name='edit student'),
    path('delete/student/<int:id>',views.deleteStudent,name='delete student'), 
    path('get/courses',getCourses.as_view(),name='get courses'), 

    path('view/registered/courses',views.registeredCourses,name='registered courses'), 

    path('drop/course/<int:id>',views.deleteRegisteredCourse,name='delete registered course'), 
    path('exam/card',views.prepExamCard,name='prepare exam card'), 

]

installation/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.auth.models import User
from django.utils.timezone import now
import environ
env=environ.Env()
environ.Env.read_env()

# Create your models here.

class SiteConstants(models.Model):
    user=models.OneToOneField(User,primary_key=True,on_delete=models.CASCADE)
    site_name=models.CharField(null=True,blank=True,max_length=100,default=env('SITE_NAME'))
    site_email=models.CharField(null=True,blank=True,max_length=100,default=env('SITE_EMAIL'))
    site_email2=models.CharField(null=True,blank=True,max_length=100,default=env('SITE_EMAIL2'))
    theme_color=models.CharField(null=True,blank=True,max_length=100,default=env('THEME_COLOR'))
    site_url=models.URLField(null=True,blank=True,default=env('SITE_URL'))
    description=models.TextField(null=True,blank=True,default=env('SITE_DESCRIPTION'))
    key_words=models.TextField(null=True,blank=True,default=env('SITE_KEYWORDS'))
    address=models.CharField(null=True,blank=True,max_length=250,default=env('SITE_ADDRESS'))
    location=models.CharField(null=True,blank=True,max_length=250,default=env('SITE_LOCATION'))
    phone=PhoneNumberField(null=True,blank=True,verbose_name='phone',unique=False,default=env('SITE_PHONE1'))
    working_days=models.CharField(null=True,blank=True,max_length=250,default="mon-fri")
    site_content=models.CharField(null=True,blank=True,max_length=250)
    working_hours=models.CharField(null=True,blank=True,max_length=250,default="8am-10pm")
    closed_days=models.CharField(null=True,blank=True,max_length=250,default="sun")
    special_days=models.CharField(null=True,blank=True,max_length=250,default="sat & holidays")
    special_hours=models.CharField(null=True,blank=True,max_length=250,default="sat & holidays")
    facebook=models.URLField(null=True,blank=True,max_length=250,default=env('FACEBOOK_LINK'))
    twitter=models.URLField(null=True,blank=True,max_length=250,default=env('TWITTER_LINK'))
    instagram=models.URLField(null=True,blank=True,max_length=250,default=env('INSTAGRAM_LINK'))
    whatsapp=models.URLField(null=True,blank=True,max_length=250,default=env('WHATSAPP_LINK'))
    linkedin=models.URLField(null=True,blank=True,max_length=250,default=env('LINKEDIN_LINK'))
    youtube=models.URLField(null=True,blank=True,max_length=250,default=env('YOUTUBE_LINK'))
    favicon=models.ImageField(null=True,blank=True,upload_to='logos/',default="logos/favicon.ico")
    icon_180=models.ImageField(null=True,blank=True,upload_to='logos/',default="favicon-180x180.png")
    icon_32=models.ImageField(null=True,blank=True,upload_to='logos/',default="favicon-32x32.png")
    icon_16=models.ImageField(null=True,blank=True,upload_to='logos/',default="favicon-16x16.png")
    created_on=models.DateTimeField(default=now)
    class Meta:
        db_table='site_constants'
        verbose_name_plural='site_constants'
    def __str__(self):
        return f'{self.user.username} site constants'

templates/panel/503.html
{% extends 'panel/base.html' %}
{% load static %}
{% block body %}
<div class="mt-4" style="margin:150px">
    <div class="container h-100">
       <div class="card">
           <div class="card-body">
                <div class="row justify-content-center h-100">
                    <div class="col-md-5">
                        <div class="form-input-content text-center">
                            <h1 class="error-text text-dark font-weight-bold">503</h1>
                            <h4 class="mt-4"><i class="fa fa-times-circle text-danger"></i> Service Unavailable</h4>
                            <p>Sorry, we are under maintenance!</p>
                                <div class="mb-5">
                                    <a class="btn btn-primary input-rounded" href="/">Back to Home</a>
                                </div>
                        </div>
                    </div>
                </div>
           </div>
       </div>
    </div>
</div>
{% endblock %}

templates/panel/add_course.html
{% extends 'panel/main.html' %}
{% load static %}
{% block body %}
<div class="row page-titles mx-0">
    <div class="col-sm-6 p-md-0">
        <div class="breadcrumb-range-picker">
            <span><i class="icon-calender"></i></span>
            <span class="ml-1">{% now 'l' %}, {% now 'd m Y' %}</span>
        </div>
    </div>
    <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
            <li class="breadcrumb-item"><a href="{% url 'courses' %}">All Courses</a></li>
            <li class="breadcrumb-item active"><a href="javascript:void(0)">Add Course</a></li>
        </ol>
    </div>
</div>
<!-- row -->
<div class="container-fluid">
    <div class="row">
        <div class="col-md-10 col-12 mx-auto">
            <div class="card position-relative">
                <div class="load-overlay" style="display:none">
                    <span class="overlay-close btn-remove" title="close overlay">
                        <i class="fa fa-close"></i>
                    </span>
                    <div class="overlay">
                        <div class="row">
                            <div class="col-12">
                                <div class="loader-container">
                                <div class="loader">
                                    <svg class="circular" viewBox="25 25 50 50">
                                    <circle class="path" cx="50" cy="50" r="10" fill="none" stroke-width="2" stroke-miterlimit="10"/>
                                    </svg>
                                </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <h4 class="card-title">Add Course</h4>
                    <form action="" class="ActiveForm" method="post" enctype="multipart/form-data" novalidate>
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6 col-12">
                                <div class="form-group">
                                    <label>School</label>
	                                <select name="school" id="single_select" class="form-control input-rounded">
	                                   	{% for school in schools %}
	                                   	<option value="{{school.school}}">{{school.school}}</option>
	                                   	{% empty %}
	                                   	<option value="" disabled="" selected="">No school found</option>
	                                   	{% endfor %}
	                                </select>
                                    <div class="feedback"></div>
                                </div>
                            </div>                            
                            <div class="col-md-6 col-12">
                                <div class="form-group">
                                    <label>Student Course name</label>
                                    {{form.course_name}}
                                    <div class="feedback"></div>
                                </div>
                            </div>
                            <div class="col-md-6 col-12">
                                <div class="form-group">
                                    <label>Tution fee</label>
                                    {{form.fee}}
                                    <div class="feedback"></div>
                                </div>
                            </div>
                           <div class="col-md-6 col-12">
	                           	<div class="form-group">               
		                            <label for="id_theme_color">Upload exam card stamp</label>
		                            <div class="custom-file" style="cursor:pointer">
		                                {{form.stamp}}
		                                <label for="customFileInput1" class="custom-file-label">Browse files</label>
		                            </div>
	                            	<div class="feedback"></div>
	                        	</div>
                           </div>
                            <div class="text-center mt-3 col-12">
                               <button class="btn btn-primary input-rounded">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/panel/courses.html
{% extends 'panel/main.html' %}
{% load static %}
{% load humanize %}
{% block body %}
<div class="row page-titles mx-0">
    <div class="col-sm-6 p-md-0">
        <div class="breadcrumb-range-picker">
            <span><i class="icon-calender"></i></span>
            <span class="ml-1">{% now 'l' %}, {% now 'd m Y' %}</span>
        </div>
    </div>
    <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/panel">Home</a></li>
            <li class="breadcrumb-item active"><a href="javascript:void(0)">All Courses</a></li>
        </ol>
    </div>
</div>
<!-- row -->
<a href="{% url 'new course' %}" class="float-btn btn btn-primary"><i class="fa fa-plus"></i></a>
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <h3 class="content-heading">All Courses</h3>
        </div>
        <div class="col-md-10 col-12 mx-auto">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">View site Courses ({{acount|intcomma}})</h4>
                    <div class="table-responsive table-results">
                        <table class="table table-responsive-sm table-stripped table-hover">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>School Name</th>
                                    <th>Tution Fee</th>
                                    <th>Exam stamp</th>
                                    <th>Course Name</th>
                                    <th>Date Created</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for course in courses %}
                                <tr id="id_{{course.id}}">
                                    <th>{{forloop.counter}}</th>
                                    <td>{{course.school}}</td>
                                    <td>Ksh:{{course.fee|intcomma|default:'0'}}</td>
                                    <td>
                                        <a class="image-preview" href="{{course.stamp.url}}" target="_blank">
                                            <i class="fa fa-file"></i> {{course.stamp}}
                                        </a>
                                    </td>
                                    <td>{{course.course_name}}</td>
                                    <td>{{course.created_on}}</td>
                                    <td>
                                        <a data-toggle="tooltip" title="Edit {{course.course_name}}"  href="{% url 'edit course' id=course.id %}" class="btn btn-success input-rounded"><i class="fa fa-edit"></i> Edit</a>
                                        <a data-host="{% url 'courses' %}" href="{% url 'delete course' id=course.id %}" data-toggle="tooltip" title="Delete {{course.course_name}}" class="del-data btn btn-danger input-rounded" type="button"><i class="fa fa-trash"></i> Delete</a>
                                    </td>
                                </tr>
                                {% empty %}
                                <tr>
                                    <td colspan="5" class="text-center">
                                        <p><i class="fa fa-excamation-circle"></i> No course(s) data found </p>
                                    </td>
                                </tr>
                                {% endfor%}
                            </tbody>
                        </table>
                    </div>
                    <ul class="pagination pagination-primary mt-4">
                        {% if courses.has_previous %}
                        <li class="page-item active"><a class="page-link" href="{% url 'courses' %}?page={{courses.previous_page_number}}"><i class="fa fa-chevron-left"></i></a></li>
                        {% endif %}
                        {% if courses.has_next %}
                        <li class="page-item active"><a class="page-link" href="{% url 'courses' %}?page={{courses.next_page_number}}"><i class="fa fa-chevron-right"></i></a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/panel/examcard.html
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <title>pdf test</title>
        <style>
            table,th,td{
                border:1px solid black;
                padding:10px;
            }
            .centre{
                text-align: center;

            }
            .image1{
                margin-left: 650px;
            }
            .image{
                margin-left: 300px;
            }
            .detail{
                margin-left: 100px;
            }
            .id{
                margin-left: 400px;
            }
            .off{
                margin-left: 70px;
            }
            
        </style>
    </head>
    <body>
        {% block content %}
        
        <div class="">
            <h1>IMAGE1</h1><h1 class="image1">IMAGE2</h1>
                <h1 class="centre">MOI UNIVERSITY 
                    <p>EXAMINATION CARD</p>
                    <p>2019/2020 ACADEMIC YEAR</p>
                </h1>
            
            <p></p>
            <div class="detail">
                <h2>Office of the Deputy Vice Chancellor (Academic Affairs)</h2>
                <p>AUTHORIZATION TO SIT UNIVERSITY EXAMINATION</p>
                <h1>TED/90/18</h1>
                <h1>MWATSUKIZI SWALEH</h1>
                <p>Bachelor of Education (Technology Education And Computer)</p>
                <p>STAGE: Y4S1 SEMESTER: SEM1 21/22</p>
            </div>
            <p class="id">##73865**</p>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">CODE</th>
                        <th scope="col">DESCRIPTION</th>
                        <th scope="col">BOOKLET NO</th>
                        <th scope="col">LECTURER SIGNATURE</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row">
                            <P>BCT 411E</P>
                            <P>BCT 421E</P>
                            <P>BCT 431E</P>
                           <P>EDU 499</P>
                           <P>EMP 410</P>
                           <P>EMP 411</P>
                           <P>TEC 400</P>
                           <P>TEC 401</P>
                           <P>TEC 490</P>
                        </th>
                        <td>
                            <P>Architectural Drawing</P>
                            <p>Structures II</p>
                            <P>Quantity Survey II</P>
                            <p>Research Project</p>
                            <p>Environmental Education</p>
                            <p>Educational Administration & Management</p>
                            <p>Technology Trip II(Week 1)</p>
                            <p>Micro Processing System</p>
                            <p>Project (Final Year)</p>

                        </td>
                       
                    </tr>
                    
                </tbody>
                

            </table>
        
            <div class="off">
            <h1>Official Signature $ Stamp:</h1>
            <p><h1>73865</h1></p>
            </div>
            
            <div class="image">
            	{{obj.site_name}}
                <img src="{{obj.stamp.}}" height="200px"/>
            	}
            </div>
        </div>
        {% endblock %}     
    </body>
</html>

templates/panel/index.html
{% extends 'panel/main.html' %}
{% load static %}
{% block body %}
<div class="row page-titles mx-0">
    <div class="col-sm-6 p-md-0">
        <div class="breadcrumb-range-picker">
            <span><i class="fa fa-clock"></i></span>
            <span class="ml-1">{% now 'l' %}, {% now 'd m Y' %}</span>
        </div>
    </div>
    <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/panel">Home</a></li>
            <li class="breadcrumb-item active"><a href="javascript:void(0)">Dashboard</a></li>
        </ol>
    </div>
</div>
<!-- row -->
<div class="container-fluid">
    <div class="row">
        <div class="col-md-4 col-12 mx-auto " style="margin-top:100px;">
            <div class="card">
                <div class="card-body">
                   <form action="{% url 'get courses' %}">
                        <div class="form-group">
                            <label for="">Select year of study</label>
                            <select name="year" id="" class="form-control input-rounded">
                                <option value="Y5">Y5</option>
                                <option value="Y4">Y4</option>
                                <option value="Y3">Y3</option>
                                <option value="Y2">Y2</option>
                                <option value="Y1">Y1</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="">Select semister of study</label>
                            <select name="sem" id="" class="form-control input-rounded">
                                <option value="S1">S1</option>
                                <option value="S2">S2</option>
                            </select>
                        </div>
                        <div class="text-center">
                            <button class="btn btn-primary input-rounded">Get Courses To Register</button>
                        </div>
                   </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/panel/new_semister.html
{% extends 'panel/main.html' %}
{% load static %}
{% block body %}
<div class="row page-titles mx-0">
    <div class="col-sm-6 p-md-0">
        <div class="breadcrumb-range-picker">
            <span><i class="icon-calender"></i></span>
            <span class="ml-1">{% now 'l' %}, {% now 'd m Y' %}</span>
        </div>
    </div>
    <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
            <li class="breadcrumb-item"><a href="{% url 'semister' %}">Semister Outline</a></li>
            <li class="breadcrumb-item active"><a href="javascript:void(0)">Add new outline</a></li>
        </ol>
    </div>
</div>
<!-- row -->
<div class="container-fluid">
    <div class="row">
        <div class="col-md-10 col-12 mx-auto">
            <div class="card position-relative">
                <div class="load-overlay" style="display:none">
                    <span class="overlay-close btn-remove" title="close overlay">
                        <i class="fa fa-close"></i>
                    </span>
                    <div class="overlay">
                        <div class="row">
                            <div class="col-12">
                                <div class="loader-container">
                                <div class="loader">
                                    <svg class="circular" viewBox="25 25 50 50">
                                    <circle class="path" cx="50" cy="50" r="10" fill="none" stroke-width="2" stroke-miterlimit="10"/>
                                    </svg>
                                </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <h4 class="card-title">Add new outline</h4>
                    <form action="" class="ActiveForm" method="post" enctype="multipart/form-data" novalidate>
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6 col-12">
                                <div class="form-group">
                                    <label>School</label>
	                                <select name="school" id="single_select" class="form-control input-rounded">
	                                   	{% for school in schools %}
	                                   	<option value="{{school.school}}">{{school.school}}</option>
	                                   	{% empty %}
	                                   	<option value="" disabled="" selected="">No school found</option>
	                                   	{% endfor %}
	                                </select>
                                    <div class="feedback"></div>
                                </div>
                            </div>                            
                            <div class="col-md-6 col-12">
                                <div class="form-group">
                                    <label>Year of study</label>
                                    {{form.year}}
                                    <div class="feedback"></div>
                                </div>
                            </div> 
                            <div class="col-md-6 col-12">
                                <div class="form-group">
                                    <label>Sem of study</label>
                                    {{form.sem}}
                                    <div class="feedback"></div>
                                </div>
                            </div> 
                            <div class="col-md-6 col-12">
                                <div class="form-group">
                                    <label>Current Academic year</label>
                                    {{form.academic_year}}
                                    <div class="feedback"></div>
                                </div>
                            </div>
                            <div class="col-md-6 col-12">
                                <div class="form-group">
                                    <label>Course name</label>
                                    <select name="course_name" class="form-control input-rounded">
	                                   	{% for course in courses %}
	                                   	<option value="{{course.course_name}}">{{course.course_name}}</option>
	                                   	{% empty %}
	                                   	<option value="" disabled="" selected="">No ccourse name found</option>
	                                   	{% endfor %}
	                                </select>
                                    <div class="feedback"></div>
                                </div>
                            </div> 
                            <div class="col-md-6 col-12">
                                <div class="form-group">
                                    <label>Course code</label>
                                    {{form.course_code}}
                                    <div class="feedback"></div>
                                </div>
                            </div> 
                            <div class="col-md-6 mx-auto col-12">
                                <div class="form-group">
                                    <label>Course title</label>
                                    {{form.course_title}}
                                    <div class="feedback"></div>
                                </div>
                            </div>
                            <div class="text-center mt-3 col-12">
                               <button class="btn btn-primary input-rounded">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/panel/prep_examcard.html
{% extends 'panel/main.html' %}
{% load static %}
{% load mathfilters %}
{% load humanize %}
{% block body %}
<div class="row page-titles mx-0">
    <div class="col-sm-6 p-md-0">
        <div class="breadcrumb-range-picker">
            <span><i class="fa fa-clock"></i></span>
            <span class="ml-1">{% now 'l' %}, {% now 'd m Y' %}</span>
        </div>
    </div>
    <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/panel">Home</a></li>
            <li class="breadcrumb-item active"><a href="javascript:void(0)">Preparing Exam Card</a></li>
        </ol>
    </div>
</div>
<!-- row -->
<div class="container-fluid">
    <div class="row">
        <div class="col-md-4 col-12 mx-auto " style="margin-top:100px;">
            <div class="card">
                <div class="card-body">
                	<div class="row">
	                	<div class="col-6">
	                	    <h4>Fee arreas:
	                	    Ksh:{{data.extendedauthuser.paid_fee|intcomma}}/Ksh:{{data.extendedauthuser.fee_balance|intcomma}} </h4>	
	                	</div>	
	                	<div class="col-6 text-right">
                            {% if percent <= 50 %}
	                		<span class="badge badge-danger p-2">{{percent}} % Complete</h3>
                            {% else %}
                            <span class="badge badge-success p-2">{{percent}} % Complete</h3>
                            {% endif %}
	                	</div>
	                	<div class="col-12 text-center">
	                		<p class="text-info">Balance:{{data.extendedauthuser.fee_balance|sub:data.extendedauthuser.paid_fee|intcomma}}</p>
	                	</div>
	                	<hr>
	                	<div class="col-12 text-center">
	                		<p>Download exam card now</p>
	                		{% if data.extendedauthuser.is_cleared %}	
	                		<a href="{% url 'download exam card' data.pk %}" class="btn btn-primary input-rounded">Download Exam card</a>
	                		{% else %}
	                		<a href="javascript:void(0);" class="btn btn-primary input-rounded">Download Exam card</a>
	                		{% endif %}
	                	</div>
                	</div>	
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}